{% set name = "dask-image" %}
{% set version = "2026.5.0" %}
{% set sha256 = "ed6b462277e691b2c12b0890ba801a0f9a00cc1894b0aa71b195a7a1419b2b00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}.*
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - dask-core >=2024.4.1
    - numpy >=1.18
    - scipy >=1.7.0
    - pims >=0.4.1
    - tifffile >=2020.10.1
  run_constrained:
    - pandas >=2.0.0
    - dask >=2024.4.1

test:
  source_files:
    - tests

  imports:
    - dask_image
    - dask.array
  requires:
    - pip
    - python {{ python_min }}.*
    - pytest >=3.0.5
    - pandas >=2.0.0
    - dask >=2024.4.1

  commands:
    - pip check
    - pytest

about:
  home: https://github.com/dask/dask-image
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Distributed image processing
  doc_url: https://dask-image.readthedocs.io/
  dev_url: https://github.com/dask/dask-image

extra:
  recipe-maintainers:
    - GenevieveBuckley
    - jakirkham
    - m-albert
