{% set name = "dask-image" %}
{% set version = "2024.5.1" %}
{% set sha256 = "d14343361878ba0dad6e2a9745fd358eb943c7ed363c1510fc4d545b543999e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python >=3.9
    - dask >=2024.4.1
    - numpy >=1.18
    - scipy >=1.7.0
    - pandas >=2.0.0
    - pims >=0.4.1
    - tifffile >=2018.10.18

test:
  source_files:
    - tests

  imports:
    - dask_image

  requires:
    - pip
    - pytest >=3.0.5

  commands:
    - pip check
    - pytest

about:
  home: https://github.com/dask/dask-image
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Distributed image processing
  doc_url: https://dask-image.readthedocs.io/
  dev_url: https://github.com/dask/dask-image

extra:
  recipe-maintainers:
    - GenevieveBuckley
    - jakirkham
    - m-albert
